# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: "npm"
          registry-url: https://registry.npmjs.org
      - uses: justgook/setup-elm@1.2.0
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      - uses: arduino/setup-protoc@v1.1.2
        with:
          version: 3.14.0
      - name: install, build and test
        run: |
          mkdir generated
          npm ci
          npm run build
          npm test
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: generated
          path: generated/Proto
